include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-arm.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - build
  - pre-package
  - package
  - post-package
  - deploy

build:
  stage: build
  image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}
  variables:
    BUILD_IMAGE_NAME: tarampampam/node
    BUILD_IMAGE_TAG: 12.16-alpine
    NG_BUILD_CONFIG_NAME: production
    NG_BUILD_OUTPUT_PATH: dist
  script:
    - npm i
    - npm run build -- -c ${NG_BUILD_CONFIG_NAME} --output-path ${NG_BUILD_OUTPUT_PATH}
  cache:
    paths:
      - node_modules/
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    paths:
      - ${NG_BUILD_OUTPUT_PATH}/
  only:
    - branches
    - tags
  except:
    - schedules

.deploy:
  variables:
    STACK: tajinaste
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
  environment:
    url: https://tajinaste.${DD_TRAEFIK_DOMAIN}
