version: '3.7'
services:
  tajinaste-manager:
    image: pedroetb/tajinaste-manager:${IMAGE_TAG:-latest}
    environment:
      - API_ORIGIN=${API_ORIGIN}/api
      - AUTH_ORIGIN=${AUTH_ORIGIN}/auth
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "80"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:tajinaste.${PUBLIC_HOSTNAME}
        traefik.backend: tajinaste-manager
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M

networks:
  traefik-net:
    external: true
