version: '3.7'

services:
  tajinaste-manager:
    image: ${TAJINASTE_MANAGER_IMAGE_NAME:-pedroetb/tajinaste-manager}:${TAJINASTE_MANAGER_IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${TAJINASTE_MANAGER_DOCKERFILE:-Dockerfile}
      args:
        NODE_IMAGE_TAG:
        NGINX_IMAGE_TAG:
        NG_BUILD_CONFIG_NAME:
    environment:
      API_ORIGIN:
      AUTH_ORIGIN:
    networks:
      traefik-net:
    healthcheck:
      test: wget --spider -q http://localhost
      interval: ${TAJINASTE_MANAGER_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${TAJINASTE_MANAGER_HEALTHCHECK_TIMEOUT:-30s}
      retries: ${TAJINASTE_MANAGER_HEALTHCHECK_RETRIES:-3}
      start_period: ${TAJINASTE_MANAGER_HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${TAJINASTE_MANAGER_REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${TAJINASTE_MANAGER_PUBLIC_HOSTNAME}
        traefik.backend: tajinaste-manager
        traefik.port: '80'
      restart_policy:
        delay: ${TAJINASTE_MANAGER_RESTART_DELAY:-10s}
        window: ${TAJINASTE_MANAGER_RESTART_WINDOW:-1m}
      resources:
        limits:
          cpus: '${TAJINASTE_MANAGER_LIMITS_CPUS:-1}'
          memory: ${TAJINASTE_MANAGER_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${TAJINASTE_MANAGER_RESERVATIONS_CPUS:-0.001}'
          memory: ${TAJINASTE_MANAGER_RESERVATIONS_MEMORY:-8M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
