version: '3.7'

services:
  tajinaste-manager:
    image: ${IMAGE_NAME:-pedroetb/tajinaste-manager}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NGINX_IMAGE_TAG:
        NG_BUILD_CONFIG_NAME:
        NG_BUILD_OUTPUT_PATH:
    environment:
      API_ORIGIN:
      AUTH_ORIGIN:
    networks:
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.tajinaste-manager.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.tajinaste-manager.tls.certresolver: ${TRAEFIK_CERTRESOLVER:-default}
        traefik.http.routers.tajinaste-manager.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.tajinaste-manager.loadbalancer.server.port: 80
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
